"""Committed protobuf bindings for the beam_agents.v1 wire and state schemas.

Generated by ``scripts/gen_proto.sh`` from ``protos/beam_agents.proto`` and
committed diff-clean (see openspec design D2). Import the message classes from
this package; never regenerate or hand-edit ``beam_agents_pb2`` directly.
"""

from beam_agents._protos.beam_agents_pb2 import (
    ActivationErrorRecord,
    AgentEnvelope,
    Continuation,
    LlmCacheBlob,
    MemoryBlob,
    ToolIntent,
    ToolResult,
    TraceEvent,
)

__all__ = [
    "ActivationErrorRecord",
    "AgentEnvelope",
    "Continuation",
    "LlmCacheBlob",
    "MemoryBlob",
    "ToolIntent",
    "ToolResult",
    "TraceEvent",
]
