/**
 * Render the backtick literals inside generated text as code spans.
 *
 * The API reference is generated by introspecting the package, so its strings
 * arrive carrying the markup their authors wrote: docstrings are
 * reStructuredText (``RunAgent``) and the module notes in `generated/api.json`
 * are markdown-flavoured (`AgentEnvelope`). Printing those delimiters is what
 * makes a generated page look unfinished.
 *
 * This changes no words. It turns markup that was already written into markup
 * a browser understands, and leaves anything unbalanced — a stray backtick, a
 * span that runs across a line break — exactly as it arrived rather than
 * guessing at what was meant.
 *
 * Used by `/api` and `/api/[symbol]`, which is why it lives here rather than
 * beside either of them.
 */

// One pattern, two uses: `SPLIT` cuts the string into alternating prose and
// literals, and `WHOLE` decides which is which. Deriving both from `LITERAL`
// is what keeps the two from drifting apart — an anchored test that no longer
// matches what the split produced would silently render markup as prose.
const LITERAL = /``[^`\n]+``|`[^`\n]+`/;
const SPLIT = new RegExp(`(${LITERAL.source})`, 'g');
const WHOLE = new RegExp(`^(?:${LITERAL.source})$`);

export function Literals({ text }: { text: string }) {
  return (
    <>
      {text.split(SPLIT).map((part, index) =>
        WHOLE.test(part) ? (
          <code key={index} className="mono">
            {part.replace(/^`+|`+$/g, '')}
          </code>
        ) : (
          part
        ),
      )}
    </>
  );
}
