import type { Metadata } from 'next';
import Link from 'next/link';
import { apiReference } from '@/lib/api';
import { absoluteUrl, SITE_NAME } from '@/lib/site';

export const metadata: Metadata = {
  title: 'API reference',
  description:
    'The declared public surface of the beam_agents package, generated by introspecting the installed package.',
  alternates: { canonical: absoluteUrl('/api') },
  openGraph: {
    title: `API reference — ${SITE_NAME}`,
    description: 'Generated from the installed package by introspection.',
    url: absoluteUrl('/api'),
  },
};

export default function ApiIndex() {
  const reference = apiReference();
  const internal = reference.modules.filter((module) => module.visibility !== 'public');

  return (
    <div className="mx-auto max-w-4xl px-5 py-10">
      <h1 className="text-[1.9rem] leading-tight font-bold tracking-tight">API reference</h1>
      <p className="mt-2 max-w-[70ch]" style={{ color: 'var(--fg-muted)' }}>
        Generated by introspecting the installed <code>beam_agents</code> package — signatures, type
        annotations, and docstrings come from the code, not from prose written alongside it.
      </p>

      <section
        className="mt-6 rounded-md border-l-4 px-4 py-3 text-sm"
        style={{
          background: 'var(--note-bg)',
          borderColor: 'var(--note-border)',
          color: 'var(--note-fg)',
        }}
      >
        <p className="font-semibold">What this covers</p>
        <p className="mt-1">
          Only the names <code>beam_agents/__init__.py</code> re-exports. The project documents
          everything else as private, and this page does not present private modules as API.
        </p>
      </section>

      <h2 className="mt-8 mb-3 text-xl font-semibold">Public surface</h2>
      <ul className="space-y-2">
        {reference.symbols.map((symbol) => (
          <li
            key={symbol.name}
            className="rounded-md border p-3"
            style={{ borderColor: 'var(--border)' }}
          >
            <div className="flex flex-wrap items-baseline gap-x-3">
              <Link
                href={`/api/${symbol.name}`}
                className="font-mono text-[0.95rem] font-semibold no-underline"
              >
                {symbol.name}
              </Link>
              <span className="text-xs" style={{ color: 'var(--fg-faint)' }}>
                {symbol.kind}
              </span>
              {symbol.requires_extra ? (
                <span className="text-xs" style={{ color: 'var(--status-experimental)' }}>
                  requires the <code>{symbol.requires_extra}</code> extra
                </span>
              ) : null}
            </div>
            <p className="mt-1 text-sm" style={{ color: 'var(--fg-muted)' }}>
              {firstLine(symbol.doc)}
            </p>
          </li>
        ))}
      </ul>

      <h2 className="mt-10 mb-3 text-xl font-semibold">Modules outside the public surface</h2>
      <p className="max-w-[70ch] text-sm" style={{ color: 'var(--fg-muted)' }}>
        Writing an agent today requires importing from modules the project documents as private.
        That gap is real and worth knowing before you depend on it: these names carry no stability
        promise, and one of them is underscore-prefixed. The site&rsquo;s examples import from this
        list and nothing else — a test enforces it.
      </p>
      <div className="table-scroll mt-3">
        <table className="w-full text-sm">
          <thead>
            <tr>
              <th scope="col" className="p-2 text-left">
                Module
              </th>
              <th scope="col" className="p-2 text-left">
                Why it is needed
              </th>
            </tr>
          </thead>
          <tbody>
            {internal.map((module) => (
              <tr key={module.module}>
                <td className="p-2 align-top">
                  <code>{module.module}</code>
                </td>
                <td className="p-2 align-top" style={{ color: 'var(--fg-muted)' }}>
                  {module.note}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-8 text-xs" style={{ color: 'var(--fg-faint)' }}>
        Generated from <code>{reference.package}</code> {reference.package_version} by{' '}
        <code>{reference.generated_by}</code>.
      </p>
    </div>
  );
}

function firstLine(doc: string | null): string {
  if (!doc) return 'No docstring.';
  return doc.split('\n')[0] ?? 'No docstring.';
}
