import type { Metadata } from 'next';
import Link from 'next/link';
import { Literals } from '@/components/Literals';
import { apiReference } from '@/lib/api';
import { absoluteUrl, SITE_NAME } from '@/lib/site';

export const metadata: Metadata = {
  title: 'API reference',
  description:
    'The declared public surface of the beam_agents package, generated by introspecting the installed package.',
  alternates: { canonical: absoluteUrl('/api') },
  openGraph: {
    title: `API reference — ${SITE_NAME}`,
    description: 'Generated from the installed package by introspection.',
    url: absoluteUrl('/api'),
  },
};

/**
 * The API reference index.
 *
 * Laid out in the landing page's language: a full-width `.shell`, hairline
 * rules between sections, and no cards. The symbol list in particular is a
 * `.list-rule` rather than a stack of bordered boxes — these are rows of one
 * table of contents, not nine separate objects, and the hairline says so.
 *
 * Everything rendered here comes from `generated/api.json`. This file decides
 * how it looks and nothing about what it says.
 */
export default function ApiIndex() {
  const reference = apiReference();
  const internal = reference.modules.filter((module) => module.visibility !== 'public');

  return (
    <>
      {/* ---------- masthead ---------- */}
      <section className="shell pt-12 pb-11 sm:pt-16 sm:pb-14">
        <p className="eyebrow">Reference · generated from the package</p>

        <h1 className="h-page mt-4 max-w-[18ch]">API reference</h1>

        <p className="lede mt-5">
          Generated by introspecting the installed <code className="mono">beam_agents</code> package
          — signatures, type annotations, and docstrings come from the code, not from prose written
          alongside it.
        </p>

        {/* A caveat, not a card. `.panel` is the flat container the design
            language allows: ground colour and a hairline, no radius worth the
            name and no shadow. */}
        <div className="panel mt-8 max-w-[64ch]">
          <p className="eyebrow" style={{ color: 'var(--ink)' }}>
            What this covers
          </p>
          <p className="mt-2 text-[0.93rem]" style={{ color: 'var(--ink-2)' }}>
            Only the names <code className="mono">beam_agents/__init__.py</code> re-exports. The
            project documents everything else as private, and this page does not present private
            modules as API.
          </p>
        </div>
      </section>

      {/* ---------- the public surface ---------- */}
      <section className="rule-top">
        <div className="shell py-12 sm:py-16">
          <div className="flex flex-wrap items-end justify-between gap-x-8 gap-y-3">
            <div>
              <p className="eyebrow">Public surface</p>
              <h2 className="h-section mt-2 max-w-[26ch]">
                {reference.symbols.length} names, each with a page of its own.
              </h2>
            </div>
            <p className="max-w-[42ch] text-[0.93rem]" style={{ color: 'var(--ink-2)' }}>
              A symbol page carries the signature the package actually declares, its docstring
              verbatim, and a link to the line it is defined on.
            </p>
          </div>

          <ul className="list-rule mt-9">
            {reference.symbols.map((symbol) => (
              <li
                key={symbol.name}
                className="grid gap-x-10 gap-y-2 sm:grid-cols-[minmax(0,15rem)_1fr]"
              >
                <div className="flex flex-wrap items-baseline gap-x-3 gap-y-2">
                  <Link
                    href={`/api/${symbol.name}`}
                    className="mono text-[0.95rem] font-medium no-underline"
                  >
                    {symbol.name}
                  </Link>
                  <span className="chip">{symbol.kind}</span>
                </div>
                <div>
                  <p className="text-[0.93rem]" style={{ color: 'var(--ink-2)' }}>
                    <Literals text={firstLine(symbol.doc)} />
                  </p>
                  {symbol.requires_extra ? (
                    // The amber stream colour is the site's standing "attend to
                    // this" hue, and it is contrast-checked against both grounds.
                    <p className="eyebrow mt-2" style={{ color: 'var(--s-intents)' }}>
                      Requires the {symbol.requires_extra} extra
                    </p>
                  ) : null}
                </div>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ---------- the gap between the public surface and real use ---------- */}
      <section className="rule-top">
        <div className="shell py-12 sm:py-16">
          <div className="flex flex-wrap items-end justify-between gap-x-8 gap-y-3">
            <div>
              <p className="eyebrow">Outside the public surface</p>
              <h2 className="h-section mt-2 max-w-[28ch]">
                Writing an agent today means importing private modules.
              </h2>
            </div>
            <p className="max-w-[42ch] text-[0.93rem]" style={{ color: 'var(--ink-2)' }}>
              That gap is real and worth knowing before you depend on it: these names carry no
              stability promise, and one of them is underscore-prefixed. The site&rsquo;s examples
              import from this list and nothing else — a test enforces it.
            </p>
          </div>

          {/* A hairline-ruled table rather than a bordered box. The wrapper
              scrolls on narrow viewports so the page body never does. */}
          <div className="mt-9 overflow-x-auto">
            <table className="w-full border-collapse text-[0.9rem]" style={{ minWidth: '36rem' }}>
              <thead>
                <tr>
                  <th
                    scope="col"
                    className="eyebrow border-b pt-0 pr-8 pb-2.5 text-left align-bottom"
                    style={{ borderColor: 'var(--rule-2)' }}
                  >
                    Module
                  </th>
                  <th
                    scope="col"
                    className="eyebrow border-b pt-0 pb-2.5 text-left align-bottom"
                    style={{ borderColor: 'var(--rule-2)' }}
                  >
                    Why it is needed
                  </th>
                </tr>
              </thead>
              <tbody>
                {internal.map((module) => (
                  <tr key={module.module}>
                    <td
                      className="mono border-b py-3.5 pr-8 align-top text-[0.85rem]"
                      style={{ borderColor: 'var(--rule)' }}
                    >
                      {module.module}
                    </td>
                    <td
                      className="border-b py-3.5 align-top"
                      style={{ borderColor: 'var(--rule)', color: 'var(--ink-2)' }}
                    >
                      <Literals text={module.note} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p className="panel--flush mono mt-10 text-[0.72rem]" style={{ color: 'var(--ink-3)' }}>
            Generated from {reference.package} {reference.package_version} by{' '}
            {reference.generated_by}.
          </p>
        </div>
      </section>
    </>
  );
}

function firstLine(doc: string | null): string {
  if (!doc) return 'No docstring.';
  return doc.split('\n')[0] ?? 'No docstring.';
}
